%% Greybox main
clc;close all;clear all;
load('greybox_test.mat');
par_set.fz_a0 = (25/1000)*(60/1000);%m^2
par_set.tau_l0 =48/1000;%m
%% Calculate wire length
testData = par_set.trial1;
temp_struct = funcKnownTerm_v3(testData);

z = iddata(temp_struct.state_array,temp_struct.u_pm.*[par_set.tau_l0,par_set.fz_a0,par_set.tau_l0,par_set.fz_a0],par_set.Ts,'Name','2-segArm');


FileName      = 'func2segODE_m';       % File describing the model structure.
Order         = [8 4 8];           % Model orders [ny nu nx].
Parameters    = ones(12,1);         % Initial parameters. Np = 3*4
InitialStates = zeros(8,1);            % Initial initial states.
Ts            = 0;                 % Time-continuous system.
nlgr = idnlgrey(FileName, Order, Parameters, InitialStates, Ts, ...
    'Name', 'Arm');
set(nlgr, 'InputName', {'tauy1','fz1','tauy2','fz2'}, ...
    'InputUnit', {'Nm','N','Nm','N'},               ...
    'OutputName', {'a1','da1','lc1','dlc1','a2','da2','lc2','dlc2'}, ...
    'OutputUnit', {'rad','rad/s','m','m/s','rad','rad/s','m','m/s'},                         ...
    'TimeUnit', 's');

nlgr = setinit(nlgr, 'Name', {'angle1'; 'velangle1'; 'clength1';'velclength1'; ...
    'angle2'; 'velangle2'; 'clength2';'velclength2';});             ...
    nlgr = setinit(nlgr, 'Unit', {'rad'; 'rad/s';'m';'m/s'; ...
    'rad'; 'rad/s';'m';'m/s'});
nlgr = setpar(nlgr, 'Name', {'amptauy1';'ampfz1';'amptauy2';'ampfz2';...
                            'ktheta1';'klc1';'ktheta2';'klc2';...
                            'dtheta1';'dlc1';'dtheta2';'dlc2';});
nlgr = setpar(nlgr, 'Unit', {'None';'None';'None';'None';...
                             'Nm/rad';'N/m';'Nm/rad';'N/m';...
                             'Nm/(rad/s)';'N/(m/s)';'Nm/(rad/s)';'N/(m/s)'});
% nlgr = setpar(nlgr, 'Minimum',{eps(0)*1;eps(0)*1;eps(0)*1;eps(0)*1;...
%                                eps(0)*1;eps(0)*1;eps(0)*1;eps(0)*1;...
%                                eps(0)*1;eps(0)*1;eps(0)*1;eps(0)*1;});   % All parameters > 0!
present(nlgr);

opt = nlgreyestOptions('Display', 'on');
nlgr = nlgreyest(z, nlgr, opt);